services:
  - type: web
    name: python-contas-pagas
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:3030 src.main:app"
